services:
  wishlist-monitor:
    image: ghcr.io/jasmeralia/amazon_wl_monitor:latest
    container_name: wishlist-monitor
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
